### ISSUE TITLE
Cannot save to "output.cpp"

### ISSUE THREAD

**Issue by MichaelSDavid** [Julgodis/Cupcake-Compiler#3]
I know this is kind of old, but I really want to play around with this fan creation of the compiler.
When ever calling the compiler with the source file as `cupcake main.jai` or whatever, there is always an error that reads:
 ```
Cupcake (v0.1-alpha)                                                                                                                                                     
Error: Module/File not found (path: .\modules\)                                                                                                                          
There were errors, exiting!
```
Basically it can never find the file or modules when called so it cannot compile. It also for some reason does not respond to command line arguments like -r, -v, -m, etc. This is on 64 bit Windows 10 and I know it says the executable is win32, but Python runs fine as a win32 executable on 64 bit Windows 10, so why shouldn't this? I heard rumours of there being a new version back in 2018, but that was never put out and we can't even fix this ourselves from showing the source. I would like to know why this behaviour is happening.

__**UPDATE: This behaviour has been fixed, the lowest post is what relates to the title of the issue now**__

**Comment by Julgodis** [comment]
Thanks for the interest in the project, though I have not been working on this for a while but I will try my best to help you out. 

```
Cupcake (v0.1-alpha)                                                                                                                                                     
Error: Module/File not found (path: .\modules\)                                                                                                                          
There were errors, exiting!
```

The compiler couldn't find the module directory with necessary files required to compile. 
Are you running `cupcake.exe` in the same directory as `modules`?
You should be able to change the directory of modules with the command line argument `-l` but I could not get that to working while testing. 

Yes the application is 32-bit (because MSVC removed support for `asm` keyword when compiling for 64-bit) and should work on Windows 64-bit without any problems. I am running it fines on my computer right now.

The command line arguments `-v` and `-r` are working for me without problems, but `-m` looks like it's completely broken.
Test this `cupcake.exe -r "print(10)"` which should output:
```
Cupcake (v0.1-alpha)                                                                                                    
10
```

There was indeed a newer version but I never had the time to finish it. If I have the time I try to look for it and release it. My expectation was the real JAI compiler would have been release already and that people would have stopped using this compiler.

**Comment by MichaelSDavid** [comment]
I have tested running `cupcake.exe` from `modules` and everywhere else too for JAI files and it spits out the same error. Still no arguments work (except for run or `-r`) and it just shows the default help text. The example `cupcake.exe -r "print(10)"` sadly did not work and still returned that same error (ran from `modules` and other directories as well as with the direct path name and not just the alias `cupcake` or `cupcake.exe`).

__**UPDATE: This behaviour has been fixed, the lowest post is what relates to the title of the issue now**__

**Comment by Julgodis** [comment]
I released the 2018 updated version with some additional fixes.
Can you try the new version and see if the same problems persists?
Here is the link for the new release: [Cupcake v0.2-alpha](https://github.com/Julgodis/Cupcake-Compiler/releases/tag/v0.2-alpha)

**Comment by MichaelSDavid** [comment]
Ok I tried it out and this is what I got from the print example:
```
Cupcake (v0.2-alpha)                                                                                                                                                     
-------------------------------------------                                                                                                                              
Workspace 'program' (10 errors, 12 reports)                                                                                                                              
.\added_strings_w1.jai:4,7: Error: Undeclared procedure (name: print)                                                                                                    
                                                                                                                                                                         
    > // Generated from unknown:0.                                                                                                                                       
    > //                                                                                                                                                                 
    > #run (print(10));                                                                                                                                                  
    > ------^                                                                                                                                                            
                                                                                                                                                                         
unknown:0,0: Error: Context type not resolved!                                                                                                                           
unknown:0,0:   ...  Do not mess around with the core.jai file!                                                                                                           
unknown:0,0:   ...  Most of the your code won't compile without the context type.                                                                                        
unknown:0,0: Error: Could not find Core Language Type 'String'                                                                                                           
unknown:0,0: Error: Could not find Core Language Type 'Any'                                                                                                              
unknown:0,0: Error: Could not find Core Language Type 'Bool'                                                                                                             
unknown:0,0: Error: Could not find Core Language Type 'Array'                                                                                                            
unknown:0,0: Error: Could not find Core Language Type 'Build_Options'                                                                                                    
unknown:0,0: Error: Could not find Core Language Type 'Context'                                                                                                          
unknown:0,0: Error: Could not find Core Language Type 'Dynamic_Array'                                                                                                    
unknown:0,0: Error: Could not find Core Language Type 'SOA_Pointer'                                                                                                      
                                                                                                                                                                         
There were errors, exiting!
```
Now at least it can find the file and modules, but these types from like `core.jai` (don't worry I did not mess with that file) say they can't be found, and #run does not recognize the function to run.

HOWEVER,
I tried use -l to specify the `modules` folder path and it kind of worked and I got something more interesting. This was for the `print(10)` example (and `---` lines just represent generic paths, it can happen anywhere):
```
Cupcake (v0.2-alpha)                                                                                                                                                     
10-------------------------------------------                                                                                                                            
Workspace 'program' (1 errors, 1 reports)                                                                                                                                
unknown:0,0: Error: Error when saving outputed c++ file. (location: C:\Users\---\cupcake-v0.2-alpha\v0.2-alpha\Windows-32-bit\---\---\output\output.cpp)          
                                                                                                                                                                         
There were errors, exiting!                                                                                                                                              
                                                                                                                                                                         
```
So now it worked out and printed 10, but it could not save to the output file. Same thing with the examples where it prints what it's supposed to but then it cannot save to the output file. And also for the `game` example, I had to use the direct path to resources to load and then the window with the game would appear. I mean, if I can see the code in the console and the game in the window as well, does it really matter if it can't output to the CPP file? I guess if you want to then compile the CPP into an EXE, like maybe for the game, that would be good.

__**UPDATE: It does create the output.cpp if I make an output folder in the same directory as the JAI file and yeah, if you have it in the same directory as `cupcake.exe` then it does save without have to provide modules or the output folder.**__

**Comment by Julgodis** [comment]
Yeah all examples now have `#run main()` which will make the code run at compile-time. If you want to generate a executable you need the C++ output. 

The problem `Error when saving outputed C++ file.` is caused by that the compiler can not find the output directory or that it doesn't have permission to write file to that directory. The output directory should be located besides the `cupcake.exe` and named `output`.  I should add a command-line option let you change this. 

Another issue had some problems building the generated C++ code and I have not tried it myself for the new updated. If it doesn't work can you create a new issue or just notify me. 

> Are you running cupcake.exe in the same directory as modules?

Yes, I am running the `cupcake.exe` besides `modules`, `output`, etc.
Here is the directory I am running from:
```
2020-05-02  13:36    <DIR>          .
2020-05-02  13:36    <DIR>          ..
2020-05-02  13:31         1 116 672 cupcake.exe
2020-05-02  13:31    <DIR>          examples
2016-06-12  15:34             1 091 LICENSE
2020-05-02  13:31    <DIR>          modules
2020-05-02  13:36    <DIR>          output
2020-05-02  13:33               712 README
2020-05-02  13:31    <DIR>          target
```
